services:
  DUMB:
    container_name: DUMB
    image: iampuid0/dumb:latest
    stop_grace_period: 30s
    shm_size: 128mb
    stdin_open: true
    tty: true
    volumes:
      - /home/username/docker/DUMB/config:/config                     ## Location of configuration files.
      - /home/username/docker/DUMB/log:/log                           ## Location for logs
      - /home/username/docker/DUMB/data:/data                         ## Location for all service data
      - /home/username/docker/DUMB/mnt/debrid:/mnt/debrid             ## Location for all symlinks and rclone mounts - change to /mnt/debrid:rshared if using decypharr 
    environment:
      - TZ=
      - PUID=
      - PGID=
    ports:
      - "3005:3005"
    devices:
      - /dev/fuse:/dev/fuse:rwm
      - /dev/dri:/dev/dri
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
